import type { Game, Hitter, Pitcher, Slate, MarketQuote, Side } from "./types";

/**
 * Demonstration slate for July 18, 2026. Pitcher / hitter ratings and reference
 * sportsbook quotes are synthetic. Sportsbook prices exist purely as comparison
 * data (PRD §1.1) — the model never sees them before pricing a game.
 */

export const PITCHERS: Record<string, Pitcher> = {
  fried: { id: "fried", name: "Max Fried", hand: "L", k9: 8.6, suppression: 0.82, expectedIP: 6.2 },
  crochet: {
    id: "crochet",
    name: "Garrett Crochet",
    hand: "L",
    k9: 11.8,
    suppression: 0.74,
    expectedIP: 6.0,
  },
  brown: {
    id: "brown",
    name: "Hunter Brown",
    hand: "R",
    k9: 10.1,
    suppression: 0.68,
    expectedIP: 6.1,
  },
  gilbert: {
    id: "gilbert",
    name: "Logan Gilbert",
    hand: "R",
    k9: 10.6,
    suppression: 0.71,
    expectedIP: 6.3,
  },
  webb: { id: "webb", name: "Logan Webb", hand: "R", k9: 8.9, suppression: 0.63, expectedIP: 6.4 },
  yamamoto: {
    id: "yamamoto",
    name: "Yoshinobu Yamamoto",
    hand: "R",
    k9: 9.8,
    suppression: 0.77,
    expectedIP: 6.0,
  },
  wheeler: {
    id: "wheeler",
    name: "Zack Wheeler",
    hand: "R",
    k9: 10.3,
    suppression: 0.86,
    expectedIP: 6.5,
  },
  sale: { id: "sale", name: "Chris Sale", hand: "L", k9: 11.2, suppression: 0.79, expectedIP: 6.0 },
  baz: { id: "baz", name: "Shane Baz", hand: "R", k9: 9.1, suppression: 0.42, expectedIP: 5.6 },
  eflin: {
    id: "eflin",
    name: "Zach Eflin",
    hand: "R",
    k9: 7.6,
    suppression: 0.38,
    expectedIP: 6.0,
  },
  peralta: {
    id: "peralta",
    name: "Freddy Peralta",
    hand: "R",
    k9: 10.4,
    suppression: 0.55,
    expectedIP: 5.7,
  },
  imanaga: {
    id: "imanaga",
    name: "Shota Imanaga",
    hand: "L",
    k9: 9.2,
    suppression: 0.5,
    expectedIP: 5.9,
  },
  gallen: {
    id: "gallen",
    name: "Zac Gallen",
    hand: "R",
    k9: 9.5,
    suppression: 0.47,
    expectedIP: 6.0,
  },
  cease: {
    id: "cease",
    name: "Dylan Cease",
    hand: "R",
    k9: 11.0,
    suppression: 0.52,
    expectedIP: 5.8,
  },
  greene: {
    id: "greene",
    name: "Hunter Greene",
    hand: "R",
    k9: 10.8,
    suppression: 0.58,
    expectedIP: 5.9,
  },
  senga: {
    id: "senga",
    name: "Kodai Senga",
    hand: "R",
    k9: 10.0,
    suppression: 0.61,
    expectedIP: 5.7,
  },
  bibee: {
    id: "bibee",
    name: "Tanner Bibee",
    hand: "R",
    k9: 8.8,
    suppression: 0.45,
    expectedIP: 6.0,
  },
  eovaldi: {
    id: "eovaldi",
    name: "Nathan Eovaldi",
    hand: "R",
    k9: 8.2,
    suppression: 0.56,
    expectedIP: 6.1,
  },
  skubal: {
    id: "skubal",
    name: "Tarik Skubal",
    hand: "L",
    k9: 11.5,
    suppression: 0.94,
    expectedIP: 6.4,
  },
  lopez: {
    id: "lopez",
    name: "Pablo López",
    hand: "R",
    k9: 9.3,
    suppression: 0.6,
    expectedIP: 6.2,
  },
  ragans: {
    id: "ragans",
    name: "Cole Ragans",
    hand: "L",
    k9: 10.5,
    suppression: 0.64,
    expectedIP: 6.0,
  },
  berrios: {
    id: "berrios",
    name: "José Berríos",
    hand: "R",
    k9: 8.4,
    suppression: 0.44,
    expectedIP: 6.1,
  },
  skenes: {
    id: "skenes",
    name: "Paul Skenes",
    hand: "R",
    k9: 11.9,
    suppression: 0.97,
    expectedIP: 6.3,
  },
  gray: { id: "gray", name: "Sonny Gray", hand: "R", k9: 9.6, suppression: 0.66, expectedIP: 6.0 },
  sears: { id: "sears", name: "JP Sears", hand: "L", k9: 7.9, suppression: 0.18, expectedIP: 5.6 },
  kikuchi: {
    id: "kikuchi",
    name: "Yusei Kikuchi",
    hand: "L",
    k9: 9.7,
    suppression: 0.51,
    expectedIP: 5.9,
  },
  alcantara: {
    id: "alcantara",
    name: "Sandy Alcantara",
    hand: "R",
    k9: 8.7,
    suppression: 0.59,
    expectedIP: 6.4,
  },
  gore: {
    id: "gore",
    name: "MacKenzie Gore",
    hand: "L",
    k9: 10.2,
    suppression: 0.49,
    expectedIP: 5.8,
  },
  freeland: {
    id: "freeland",
    name: "Kyle Freeland",
    hand: "L",
    k9: 6.4,
    suppression: -0.22,
    expectedIP: 5.7,
  },
  martin: {
    id: "martin",
    name: "Davis Martin",
    hand: "R",
    k9: 7.7,
    suppression: 0.08,
    expectedIP: 5.5,
  },
};

export const HITTERS: Record<string, Hitter> = {
  judge: {
    id: "judge",
    name: "Aaron Judge",
    teamCode: "NYY",
    hand: "R",
    pa: 4.3,
    rates: { bb: 0.16, single: 0.12, double: 0.05, triple: 0.003, hr: 0.088 },
  },
  julio: {
    id: "julio",
    name: "Julio Rodríguez",
    teamCode: "SEA",
    hand: "R",
    pa: 4.2,
    rates: { bb: 0.08, single: 0.15, double: 0.05, triple: 0.006, hr: 0.045 },
  },
  raleigh: {
    id: "raleigh",
    name: "Cal Raleigh",
    teamCode: "SEA",
    hand: "S",
    pa: 4.1,
    rates: { bb: 0.1, single: 0.1, double: 0.04, triple: 0.002, hr: 0.062 },
  },
  yordan: {
    id: "yordan",
    name: "Yordan Alvarez",
    teamCode: "HOU",
    hand: "L",
    pa: 4.2,
    rates: { bb: 0.13, single: 0.14, double: 0.055, triple: 0.003, hr: 0.07 },
  },
  altuve: {
    id: "altuve",
    name: "Jose Altuve",
    teamCode: "HOU",
    hand: "R",
    pa: 4.3,
    rates: { bb: 0.07, single: 0.16, double: 0.048, triple: 0.005, hr: 0.038 },
  },
  ohtani: {
    id: "ohtani",
    name: "Shohei Ohtani",
    teamCode: "LAD",
    hand: "L",
    pa: 4.4,
    rates: { bb: 0.14, single: 0.13, double: 0.05, triple: 0.008, hr: 0.082 },
  },
  betts: {
    id: "betts",
    name: "Mookie Betts",
    teamCode: "LAD",
    hand: "R",
    pa: 4.3,
    rates: { bb: 0.11, single: 0.15, double: 0.05, triple: 0.004, hr: 0.048 },
  },
  chapman: {
    id: "chapman",
    name: "Matt Chapman",
    teamCode: "SFG",
    hand: "R",
    pa: 4.1,
    rates: { bb: 0.1, single: 0.12, double: 0.045, triple: 0.003, hr: 0.045 },
  },
  acuna: {
    id: "acuna",
    name: "Ronald Acuña Jr.",
    teamCode: "ATL",
    hand: "R",
    pa: 4.3,
    rates: { bb: 0.12, single: 0.16, double: 0.05, triple: 0.006, hr: 0.055 },
  },
  harper: {
    id: "harper",
    name: "Bryce Harper",
    teamCode: "PHI",
    hand: "L",
    pa: 4.3,
    rates: { bb: 0.13, single: 0.14, double: 0.052, triple: 0.004, hr: 0.06 },
  },
  schwarber: {
    id: "schwarber",
    name: "Kyle Schwarber",
    teamCode: "PHI",
    hand: "L",
    pa: 4.2,
    rates: { bb: 0.14, single: 0.09, double: 0.04, triple: 0.002, hr: 0.068 },
  },
  yandy: {
    id: "yandy",
    name: "Yandy Díaz",
    teamCode: "TBR",
    hand: "R",
    pa: 4.2,
    rates: { bb: 0.09, single: 0.16, double: 0.045, triple: 0.002, hr: 0.036 },
  },
};

const ml = (side: Side, american: number): MarketQuote => ({ kind: "moneyline", side, american });
const tot = (side: Side, line: number, american: number): MarketQuote => ({
  kind: "total",
  side,
  line,
  american,
});
const pk = (playerId: string, side: Side, line: number, american: number): MarketQuote => ({
  kind: "pitcher_k",
  side,
  line,
  playerId,
  american,
});
const per = (playerId: string, side: Side, line: number, american: number): MarketQuote => ({
  kind: "pitcher_er",
  side,
  line,
  playerId,
  american,
});
const htb = (playerId: string, line: number, american: number): MarketQuote => ({
  kind: "hitter_tb",
  side: "over",
  line,
  playerId,
  american,
});

export const SLATE: Slate = {
  date: "2026-07-18",
  games: [
    {
      id: "bos-nyy",
      startTimeET: "7:05 PM ET",
      venue: "Yankee Stadium",
      awayCode: "BOS",
      homeCode: "NYY",
      awayPitcherId: "crochet",
      homePitcherId: "fried",
      weather: { tempF: 81, windMph: 9, windDir: "out to right", roof: "none", runFactor: 1.05 },
      dataQuality: 0.98,
      lineupCertainty: 0.96,
      marketStability: 0.58,
      featuredHitterIds: ["judge"],
      markets: [
        ml("home", -148),
        ml("away", 126),
        tot("over", 8.0, 100),
        tot("under", 8.0, -120),
        pk("fried", "over", 5.5, -120),
        pk("fried", "under", 5.5, -100),
        pk("crochet", "over", 6.5, -115),
        htb("judge", 1.5, 135),
      ],
    },
    {
      id: "sea-hou",
      startTimeET: "8:10 PM ET",
      venue: "Daikin Park · Roof closed",
      awayCode: "SEA",
      homeCode: "HOU",
      awayPitcherId: "gilbert",
      homePitcherId: "brown",
      weather: { tempF: 74, windMph: 0, windDir: "calm", roof: "closed", runFactor: 0.97 },
      dataQuality: 0.96,
      lineupCertainty: 0.93,
      marketStability: 0.82,
      featuredHitterIds: ["julio", "raleigh", "yordan", "altuve"],
      markets: [
        ml("home", -132),
        ml("away", 112),
        tot("over", 8.0, -105),
        tot("under", 8.0, -115),
        pk("gilbert", "over", 6.5, 105),
        pk("gilbert", "under", 6.5, -125),
        pk("brown", "over", 6.5, -110),
        per("brown", "under", 2.5, 115),
        per("brown", "over", 2.5, -140),
        htb("yordan", 1.5, 118),
        htb("altuve", 1.5, 155),
      ],
    },
    {
      id: "lad-sfg",
      startTimeET: "9:45 PM ET",
      venue: "Oracle Park",
      awayCode: "LAD",
      homeCode: "SFG",
      awayPitcherId: "yamamoto",
      homePitcherId: "webb",
      weather: { tempF: 62, windMph: 16, windDir: "in from center", roof: "none", runFactor: 0.9 },
      dataQuality: 0.95,
      lineupCertainty: 0.9,
      marketStability: 0.74,
      featuredHitterIds: ["ohtani", "betts", "chapman"],
      markets: [
        ml("away", -138),
        ml("home", 118),
        tot("over", 7.5, -108),
        tot("under", 7.5, -112),
        pk("yamamoto", "over", 6.5, -105),
        pk("webb", "over", 5.5, -115),
        htb("ohtani", 1.5, 128),
        htb("betts", 1.5, 150),
      ],
    },
    {
      id: "atl-phi",
      startTimeET: "6:40 PM ET",
      venue: "Citizens Bank Park",
      awayCode: "ATL",
      homeCode: "PHI",
      awayPitcherId: "sale",
      homePitcherId: "wheeler",
      weather: { tempF: 84, windMph: 7, windDir: "out to left", roof: "none", runFactor: 1.04 },
      dataQuality: 0.97,
      lineupCertainty: 0.94,
      marketStability: 0.69,
      featuredHitterIds: ["acuna", "harper", "schwarber"],
      markets: [
        ml("home", -122),
        ml("away", 104),
        tot("over", 8.0, -110),
        tot("under", 8.0, -110),
        pk("sale", "over", 6.5, -120),
        pk("wheeler", "over", 6.5, -125),
        htb("harper", 1.5, 132),
        htb("schwarber", 1.5, 140),
      ],
    },
    {
      id: "bal-tbr",
      startTimeET: "7:05 PM ET",
      venue: "Tropicana Field",
      awayCode: "BAL",
      homeCode: "TBR",
      awayPitcherId: "eflin",
      homePitcherId: "baz",
      weather: { tempF: 72, windMph: 0, windDir: "calm", roof: "closed", runFactor: 0.98 },
      dataQuality: 0.94,
      lineupCertainty: 0.88,
      marketStability: 0.77,
      featuredHitterIds: ["yandy"],
      markets: [
        ml("away", -118),
        ml("home", 100),
        tot("over", 8.5, -105),
        tot("under", 8.5, -115),
        htb("yandy", 1.5, 158),
      ],
    },
    {
      id: "chc-mil",
      startTimeET: "8:10 PM ET",
      venue: "American Family Field",
      awayCode: "CHC",
      homeCode: "MIL",
      awayPitcherId: "imanaga",
      homePitcherId: "peralta",
      weather: { tempF: 79, windMph: 6, windDir: "out to right", roof: "open", runFactor: 1.0 },
      dataQuality: 0.95,
      lineupCertainty: 0.91,
      marketStability: 0.8,
      featuredHitterIds: [],
      markets: [
        ml("home", -126),
        ml("away", 108),
        tot("over", 7.5, -112),
        tot("under", 7.5, -108),
        pk("peralta", "over", 6.5, -110),
      ],
    },
    {
      id: "sdp-ari",
      startTimeET: "9:40 PM ET",
      venue: "Chase Field",
      awayCode: "SDP",
      homeCode: "ARI",
      awayPitcherId: "cease",
      homePitcherId: "gallen",
      weather: { tempF: 88, windMph: 0, windDir: "calm", roof: "closed", runFactor: 1.02 },
      dataQuality: 0.93,
      lineupCertainty: 0.87,
      marketStability: 0.72,
      featuredHitterIds: [],
      markets: [
        ml("away", -114),
        ml("home", -104),
        tot("over", 8.5, -110),
        tot("under", 8.5, -110),
        pk("cease", "over", 7.5, -105),
        pk("gallen", "over", 6.5, -115),
      ],
    },
    {
      id: "nym-cin",
      startTimeET: "6:40 PM ET",
      venue: "Great American Ball Park",
      awayCode: "NYM",
      homeCode: "CIN",
      awayPitcherId: "senga",
      homePitcherId: "greene",
      weather: { tempF: 86, windMph: 11, windDir: "out to right", roof: "none", runFactor: 1.09 },
      dataQuality: 0.92,
      lineupCertainty: 0.85,
      marketStability: 0.66,
      featuredHitterIds: [],
      markets: [
        ml("away", -110),
        ml("home", -108),
        tot("over", 9.0, -108),
        tot("under", 9.0, -112),
        pk("greene", "over", 7.5, -110),
      ],
    },
    {
      id: "tex-cle",
      startTimeET: "7:10 PM ET",
      venue: "Progressive Field",
      awayCode: "TEX",
      homeCode: "CLE",
      awayPitcherId: "eovaldi",
      homePitcherId: "bibee",
      weather: { tempF: 77, windMph: 8, windDir: "in from left", roof: "none", runFactor: 0.98 },
      dataQuality: 0.96,
      lineupCertainty: 0.9,
      marketStability: 0.81,
      featuredHitterIds: [],
      markets: [ml("home", -120), ml("away", 102), tot("over", 7.5, -110), tot("under", 7.5, -110)],
    },
    {
      id: "min-det",
      startTimeET: "6:40 PM ET",
      venue: "Comerica Park",
      awayCode: "MIN",
      homeCode: "DET",
      awayPitcherId: "lopez",
      homePitcherId: "skubal",
      weather: { tempF: 75, windMph: 9, windDir: "out to center", roof: "none", runFactor: 0.96 },
      dataQuality: 0.97,
      lineupCertainty: 0.92,
      marketStability: 0.85,
      featuredHitterIds: [],
      markets: [
        ml("home", -168),
        ml("away", 142),
        tot("over", 7.0, -105),
        tot("under", 7.0, -115),
        pk("skubal", "over", 7.5, -120),
      ],
    },
    {
      id: "tor-kcr",
      startTimeET: "8:10 PM ET",
      venue: "Kauffman Stadium",
      awayCode: "TOR",
      homeCode: "KCR",
      awayPitcherId: "berrios",
      homePitcherId: "ragans",
      weather: { tempF: 83, windMph: 10, windDir: "out to right", roof: "none", runFactor: 1.0 },
      dataQuality: 0.94,
      lineupCertainty: 0.89,
      marketStability: 0.78,
      featuredHitterIds: [],
      markets: [
        ml("home", -124),
        ml("away", 106),
        tot("over", 8.0, -110),
        tot("under", 8.0, -110),
        pk("ragans", "over", 6.5, -110),
      ],
    },
    {
      id: "stl-pit",
      startTimeET: "6:35 PM ET",
      venue: "PNC Park",
      awayCode: "STL",
      homeCode: "PIT",
      awayPitcherId: "gray",
      homePitcherId: "skenes",
      weather: { tempF: 78, windMph: 7, windDir: "in from right", roof: "none", runFactor: 0.95 },
      dataQuality: 0.96,
      lineupCertainty: 0.91,
      marketStability: 0.83,
      featuredHitterIds: [],
      markets: [
        ml("home", -156),
        ml("away", 132),
        tot("over", 7.0, -108),
        tot("under", 7.0, -112),
        pk("skenes", "over", 7.5, -130),
      ],
    },
    {
      id: "laa-ath",
      startTimeET: "9:40 PM ET",
      venue: "Sutter Health Park",
      awayCode: "LAA",
      homeCode: "ATH",
      awayPitcherId: "kikuchi",
      homePitcherId: "sears",
      weather: { tempF: 90, windMph: 12, windDir: "out to left", roof: "none", runFactor: 1.05 },
      dataQuality: 0.9,
      lineupCertainty: 0.83,
      marketStability: 0.61,
      featuredHitterIds: [],
      markets: [
        ml("away", -112),
        ml("home", -106),
        tot("over", 9.0, -110),
        tot("under", 9.0, -110),
      ],
    },
    {
      id: "wsn-mia",
      startTimeET: "6:40 PM ET",
      venue: "loanDepot Park",
      awayCode: "WSN",
      homeCode: "MIA",
      awayPitcherId: "gore",
      homePitcherId: "alcantara",
      weather: { tempF: 76, windMph: 0, windDir: "calm", roof: "closed", runFactor: 0.94 },
      dataQuality: 0.91,
      lineupCertainty: 0.84,
      marketStability: 0.7,
      featuredHitterIds: [],
      markets: [
        ml("home", -118),
        ml("away", 100),
        tot("over", 7.5, -110),
        tot("under", 7.5, -110),
        pk("gore", "over", 6.5, -110),
      ],
    },
    {
      id: "chw-col",
      startTimeET: "8:40 PM ET",
      venue: "Coors Field",
      awayCode: "CHW",
      homeCode: "COL",
      awayPitcherId: "martin",
      homePitcherId: "freeland",
      weather: { tempF: 85, windMph: 8, windDir: "out to center", roof: "none", runFactor: 1.18 },
      dataQuality: 0.89,
      lineupCertainty: 0.82,
      marketStability: 0.55,
      featuredHitterIds: [],
      markets: [
        ml("home", -110),
        ml("away", -108),
        tot("over", 11.0, -110),
        tot("under", 11.0, -110),
      ],
    },
  ],
};

export function pitcher(id: string): Pitcher {
  const p = PITCHERS[id];
  if (!p) throw new Error(`Unknown pitcher: ${id}`);
  return p;
}
export function hitter(id: string): Hitter {
  const h = HITTERS[id];
  if (!h) throw new Error(`Unknown hitter: ${id}`);
  return h;
}
export function gameById(id: string): Game | undefined {
  return SLATE.games.find((g) => g.id === id);
}
