import type { Team } from "./types";

/**
 * 30-team reference table. Ratings are synthetic model feature inputs for the
 * demonstration slate (offense/defense in runs-vs-average, bullpen fatigue 0–1,
 * home park run factor). They feed the Forecast and Simulation engines.
 */
export const TEAMS: Record<string, Team> = {
  NYY: {
    code: "NYY",
    city: "New York",
    name: "Yankees",
    league: "AL",
    division: "East",
    offense: 0.62,
    bullpenFatigue: 0.28,
    defense: 0.14,
    parkFactor: 1.06,
  },
  BOS: {
    code: "BOS",
    city: "Boston",
    name: "Red Sox",
    league: "AL",
    division: "East",
    offense: 0.34,
    bullpenFatigue: 0.41,
    defense: -0.06,
    parkFactor: 1.08,
  },
  TBR: {
    code: "TBR",
    city: "Tampa Bay",
    name: "Rays",
    league: "AL",
    division: "East",
    offense: 0.08,
    bullpenFatigue: 0.33,
    defense: 0.22,
    parkFactor: 0.97,
  },
  TOR: {
    code: "TOR",
    city: "Toronto",
    name: "Blue Jays",
    league: "AL",
    division: "East",
    offense: 0.21,
    bullpenFatigue: 0.37,
    defense: 0.05,
    parkFactor: 1.01,
  },
  BAL: {
    code: "BAL",
    city: "Baltimore",
    name: "Orioles",
    league: "AL",
    division: "East",
    offense: 0.44,
    bullpenFatigue: 0.3,
    defense: 0.09,
    parkFactor: 1.03,
  },
  CLE: {
    code: "CLE",
    city: "Cleveland",
    name: "Guardians",
    league: "AL",
    division: "Central",
    offense: 0.02,
    bullpenFatigue: 0.22,
    defense: 0.28,
    parkFactor: 0.98,
  },
  DET: {
    code: "DET",
    city: "Detroit",
    name: "Tigers",
    league: "AL",
    division: "Central",
    offense: 0.12,
    bullpenFatigue: 0.31,
    defense: 0.11,
    parkFactor: 0.96,
  },
  KCR: {
    code: "KCR",
    city: "Kansas City",
    name: "Royals",
    league: "AL",
    division: "Central",
    offense: 0.05,
    bullpenFatigue: 0.39,
    defense: 0.03,
    parkFactor: 1.0,
  },
  MIN: {
    code: "MIN",
    city: "Minnesota",
    name: "Twins",
    league: "AL",
    division: "Central",
    offense: 0.18,
    bullpenFatigue: 0.35,
    defense: 0.07,
    parkFactor: 1.0,
  },
  CHW: {
    code: "CHW",
    city: "Chicago",
    name: "White Sox",
    league: "AL",
    division: "Central",
    offense: -0.38,
    bullpenFatigue: 0.52,
    defense: -0.19,
    parkFactor: 1.02,
  },
  HOU: {
    code: "HOU",
    city: "Houston",
    name: "Astros",
    league: "AL",
    division: "West",
    offense: 0.4,
    bullpenFatigue: 0.26,
    defense: 0.16,
    parkFactor: 1.0,
  },
  SEA: {
    code: "SEA",
    city: "Seattle",
    name: "Mariners",
    league: "AL",
    division: "West",
    offense: 0.14,
    bullpenFatigue: 0.24,
    defense: 0.2,
    parkFactor: 0.94,
  },
  TEX: {
    code: "TEX",
    city: "Texas",
    name: "Rangers",
    league: "AL",
    division: "West",
    offense: 0.27,
    bullpenFatigue: 0.34,
    defense: 0.01,
    parkFactor: 1.03,
  },
  LAA: {
    code: "LAA",
    city: "Los Angeles",
    name: "Angels",
    league: "AL",
    division: "West",
    offense: -0.06,
    bullpenFatigue: 0.44,
    defense: -0.09,
    parkFactor: 0.99,
  },
  ATH: {
    code: "ATH",
    city: "Athletics",
    name: "Athletics",
    league: "AL",
    division: "West",
    offense: -0.22,
    bullpenFatigue: 0.48,
    defense: -0.12,
    parkFactor: 1.04,
  },
  ATL: {
    code: "ATL",
    city: "Atlanta",
    name: "Braves",
    league: "NL",
    division: "East",
    offense: 0.5,
    bullpenFatigue: 0.27,
    defense: 0.13,
    parkFactor: 1.02,
  },
  NYM: {
    code: "NYM",
    city: "New York",
    name: "Mets",
    league: "NL",
    division: "East",
    offense: 0.31,
    bullpenFatigue: 0.32,
    defense: 0.06,
    parkFactor: 0.98,
  },
  PHI: {
    code: "PHI",
    city: "Philadelphia",
    name: "Phillies",
    league: "NL",
    division: "East",
    offense: 0.46,
    bullpenFatigue: 0.29,
    defense: 0.08,
    parkFactor: 1.01,
  },
  WSN: {
    code: "WSN",
    city: "Washington",
    name: "Nationals",
    league: "NL",
    division: "East",
    offense: -0.08,
    bullpenFatigue: 0.42,
    defense: -0.05,
    parkFactor: 1.0,
  },
  MIA: {
    code: "MIA",
    city: "Miami",
    name: "Marlins",
    league: "NL",
    division: "East",
    offense: -0.24,
    bullpenFatigue: 0.45,
    defense: -0.02,
    parkFactor: 0.95,
  },
  MIL: {
    code: "MIL",
    city: "Milwaukee",
    name: "Brewers",
    league: "NL",
    division: "Central",
    offense: 0.19,
    bullpenFatigue: 0.23,
    defense: 0.24,
    parkFactor: 1.0,
  },
  CHC: {
    code: "CHC",
    city: "Chicago",
    name: "Cubs",
    league: "NL",
    division: "Central",
    offense: 0.33,
    bullpenFatigue: 0.31,
    defense: 0.1,
    parkFactor: 1.02,
  },
  STL: {
    code: "STL",
    city: "St. Louis",
    name: "Cardinals",
    league: "NL",
    division: "Central",
    offense: 0.09,
    bullpenFatigue: 0.36,
    defense: 0.12,
    parkFactor: 0.99,
  },
  CIN: {
    code: "CIN",
    city: "Cincinnati",
    name: "Reds",
    league: "NL",
    division: "Central",
    offense: 0.15,
    bullpenFatigue: 0.38,
    defense: -0.03,
    parkFactor: 1.09,
  },
  PIT: {
    code: "PIT",
    city: "Pittsburgh",
    name: "Pirates",
    league: "NL",
    division: "Central",
    offense: -0.16,
    bullpenFatigue: 0.4,
    defense: 0.04,
    parkFactor: 0.97,
  },
  LAD: {
    code: "LAD",
    city: "Los Angeles",
    name: "Dodgers",
    league: "NL",
    division: "West",
    offense: 0.66,
    bullpenFatigue: 0.25,
    defense: 0.15,
    parkFactor: 1.0,
  },
  SDP: {
    code: "SDP",
    city: "San Diego",
    name: "Padres",
    league: "NL",
    division: "West",
    offense: 0.29,
    bullpenFatigue: 0.28,
    defense: 0.19,
    parkFactor: 0.93,
  },
  SFG: {
    code: "SFG",
    city: "San Francisco",
    name: "Giants",
    league: "NL",
    division: "West",
    offense: 0.07,
    bullpenFatigue: 0.3,
    defense: 0.14,
    parkFactor: 0.92,
  },
  ARI: {
    code: "ARI",
    city: "Arizona",
    name: "Diamondbacks",
    league: "NL",
    division: "West",
    offense: 0.35,
    bullpenFatigue: 0.34,
    defense: 0.02,
    parkFactor: 1.05,
  },
  COL: {
    code: "COL",
    city: "Colorado",
    name: "Rockies",
    league: "NL",
    division: "West",
    offense: 0.02,
    bullpenFatigue: 0.5,
    defense: -0.16,
    parkFactor: 1.18,
  },
};

export function team(code: string): Team {
  const t = TEAMS[code];
  if (!t) throw new Error(`Unknown team code: ${code}`);
  return t;
}
